### ISSUE TITLE
Sum taken over wrong axis 

### ISSUE THREAD

**Issue by bchugg** [scikit-learn-contrib/forest-confidence-interval#104]
Hi there, 

I believe the centered predictions are being computed incorrectly. Line 278 in `forestci.py` takes the average over the _predictions_, as opposed to the trees. The resulting shape of `pred_mean` is `(forest.n_estimators,)` when it should be `(X_test.shape[0],)`. See below:  

https://github.com/scikit-learn-contrib/forest-confidence-interval/blob/6d2a9c285b96bd415ad5ed03f37e517740a47fa2/forestci/forestci.py#L278

Thanks for the great package otherwise! :)

**Comment by nikaashpuri** [comment]
are there any thoughts on this one?

**Comment by nikaashpuri** [comment]
please check https://github.com/scikit-learn-contrib/forest-confidence-interval/issues/80

**Comment by danieleongari** [comment]
`pred_mean` is correct to compute the variance of `pred`. I guess you missed that the matrix `pred` is trasposed.
