### ISSUE TITLE
Can this package be adapted to perform Thompson sampling?

### ISSUE THREAD

**Issue by douglasmason** [scikit-learn-contrib/forest-confidence-interval#105]
I’m looking at using random forest regressors to perform hyperparameter tuning in a Bayesian optimization setup. While you can use the upper confidence bound to explore your state space, Thompson sampling performs better and eliminates the need for tuning the hyper-hyperparameter of the confidence interval used for selection. One solution is to obtain an empirical Bayesian posterior by training many random forest regressors on bootstrapped data, but this seems like overkill (ensembles of ensembles!). Would appreciate any input on the subject thank you! (For more discussion see this review of using CART decision trees to pull off the goal: https://arxiv.org/pdf/1706.04687.pdf)

**Comment by danieleongari** [comment]
This package provides the confidence interval not the acquisition function!
