### ISSUE TITLE
Compatibility issues with scikit-learn 0.24.2

### ISSUE THREAD

**Issue by alliMD** [scikit-learn-contrib/forest-confidence-interval#106]
Hi, I was wondering if you will be ensuring compatibility with newer versions of scikit-learn? sklearn.ensemble.forest was renamed to sklearn.ensemble._forest in 2019 so I'm having this error 

```
from sklearn.ensemble.forest import _generate_sample_indices, _get_n_samples_bootstrap

ModuleNotFoundError: No module named 'sklearn.ensemble.forest'
```

**Comment by arokem** [comment]
This is already implemented in the `master` branch, so if you install from source you should be good to go. I will also push out a new release.
