### ISSUE TITLE
Installation with pip doesn't work.

### ISSUE THREAD

**Issue by valignatev** [scikit-learn-contrib/forest-confidence-interval#16]
Hello, when trying to install through `pip install sklforestci`, got an error `Could not find a version that satisfies the requirement sklforestci (from versions: )
No matching distribution found for sklforestci`.

So I have to install it directly from github: `pip install git+https://github.com/uwescience/sklearn-forest-ci.git`.

Is module missing from pypi?

**Comment by arokem** [comment]
Sorry - the documentation is misleading. We are in the process of moving this work into the "scikit-learn-contrib" organization, and renaming this, so for the time being we have not uploaded this to PyPi, until we finish that process.

For the time being, you will have to install this from the `master` source code.
