### ISSUE TITLE
Specify the statistical quantity for which the variance is computed

### ISSUE THREAD

**Issue by glouppe** [scikit-learn-contrib/forest-confidence-interval#19]
Hi! Great project! and welcome to scikit-learn-contrib :)

I could not find the information other than by looking at the code myself, but it would be good to specify precisely the variance of what statistical quantity is computed/approximated, and over which distribution. What is meant by "confidence interval" may otherwise be misleading/confusing.

**Comment by arokem** [comment]
https://github.com/scikit-learn-contrib/forest-confidence-interval/commit/9837f31ec438b7753c3ad1b80e066f6f4127e0e3

**Comment by arokem** [comment]
I think this is handled in that commit. Closing for now, but feel free to reopen if you think we haven't properly addressed your comment.
