### ISSUE TITLE
JOSS Review "License" [Blocker]

### ISSUE THREAD

**Issue by DannyArends** [scikit-learn-contrib/forest-confidence-interval#27]
LICENCE file is not an OSI approved licence

**Comment by kpolimis** [comment]
license changed to : MIT open source license

**Comment by arokem** [comment]
Addressed in https://github.com/scikit-learn-contrib/forest-confidence-interval/commit/61abf19f0a4f49a0fe23a27ef4d6d00192f53e06

**Comment by DannyArends** [comment]
The the license provided is still **NOT** the official MIT license, as provided by the open source foundation at https://opensource.org/licenses/MIT

The words: "All rights reserved." do **NOT** occur in the MIT license, and should be removed.
The first line should read, (remove the (c), the comma (,) and please add the affiliation to the first line):

Copyright 2016 Ariel Rokem, Bryna Hazelton, Kivan Polimis (The University of Washington, eScience Institute)

When you want to use the MIT license, please copy the license verbatim from: https://opensource.org/licenses/MIT

**Comment by arokem** [comment]
Sorry about that. How's that? #53
