### ISSUE TITLE
JOSS Review "Automated tests" [Blocker]

### ISSUE THREAD

**Issue by DannyArends** [scikit-learn-contrib/forest-confidence-interval#33]
There is no mention of tests, or how to run the tests in the documentation. Also the level of test coverage for this package is unknown

**Comment by kpolimis** [comment]
Added: "Requires installation of nose package. Tests are located in the forestci/tests folder and can be run with the nosetests command in the main directory" to README

**Comment by arokem** [comment]
Closed through #52
