### ISSUE TITLE
JOSS Review "Community guidelines" [Blocker]

### ISSUE THREAD

**Issue by DannyArends** [scikit-learn-contrib/forest-confidence-interval#34]
Please provide guidelines in the README.md file for others to 
1) Contribute to the software 
2) Report issues or problems with the software 
3) Seek support

**Comment by kpolimis** [comment]
Contributions to address any of the issues in the issue log are very welcome. Please submit improvements as pull requests against the repo after verifying that the existing tests pass and any new code is well covered by unit tests.

Bug reports are also appreciated, please add them to the issue log after verifying that the issue does not already exist. Comments on existing issues are also welcome.

Please e-mail [Ariel Rokem](mailto:arokem@gmail.com), [Kivan Polimis](mailto:kivan.polimis@gmail.com), or [Bryna Hazelton](brynah@phys.washington.edu ) if you have any questions, suggestions or feedback.

**Comment by arokem** [comment]
Closed through #46
