### ISSUE TITLE
TypeError when following examples - docs need updating.

### ISSUE THREAD

**Issue by lesterlitch** [scikit-learn-contrib/forest-confidence-interval#41]
Hey guys,

Current example in docs no longer runs with latest version from pip, producing the error:

mpg_V_IJ_unbiased = fci.random_forest_error(mpg_forest, mpg_X_train, mpg_X_test)
TypeError: random_forest_error() takes exactly 4 arguments (3 given)

This is because the random_forest_error method inputs have changed to request the in_bag argument second.

This is a cool library, not sure how this normally works but want me to amend the docs?

**Comment by arokem** [comment]
I believe this is the same issue as #40. We just still haven't released a new version with the API that is described in the docs.

**Comment by lesterlitch** [comment]
Ah cool. Cheers. Will close.
