### ISSUE TITLE
pip install will install version 0.1 instead of 0.2

### ISSUE THREAD

**Issue by stasSajin** [scikit-learn-contrib/forest-confidence-interval#43]
Hi,

Running pip install will install version 0.1 from here https://pypi.python.org/pypi/forestci. The version on github and the documentation reflects changes in forestci 0.2. I suggest updating the versioning on pip or suggesting that users install the latest development version using:

`pip install git+git://github.com/scikit-learn-contrib/forest-confidence-interval.git`

**Comment by arokem** [comment]
Closed through #52
