### ISSUE TITLE
Negative error values in classification task

### ISSUE THREAD

**Issue by ericmjl** [scikit-learn-contrib/forest-confidence-interval#61]
Not sure whether this is an issue or not, but I thought I'd report it.

To the best of my knowledge, confidence intervals are, by definition, supposed to be positively-valued. However, I noticed that I am getting negative CIs. For example, after fitting a classifier and then obtaining confidence interval values, I see the following distribution:

![ci](https://user-images.githubusercontent.com/2631566/32500398-4acff20c-c3a3-11e7-9a15-ffba7ba0d526.jpg)

When I check the range of the confidence intervals, I get:

```
>>> np.percentile(pred_error, [0, 1, 2, 5, 10, 57, 58])
array([ -6.44598321e-02,  -3.91696053e-02,  -2.07770770e-02,
        -2.43449960e-03,  -7.71852754e-04,  -4.55220853e-05,
         2.72525240e-05])
```

Negative values occur up to the 57th percentile.

Something didn't make sense w.r.t. negative CI values, thus I felt compelled to report this here. Hope it comes in handy.

**Comment by arokem** [comment]
Thanks for reporting. This should be addressed by
https://github.com/scikit-learn-contrib/forest-confidence-interval/pull/49

**Comment by arokem** [comment]
This should be resolved by the new release that we just pushed out. But feel free to reopen, if that didn't work for you.
