### ISSUE TITLE
Paper describing work?

### ISSUE THREAD

**Issue by ericmjl** [scikit-learn-contrib/forest-confidence-interval#68]
I remember there's supposed to be a publication describing this work; is it out somewhere?

**Comment by arokem** [comment]
The paper is out in JOSS:
http://joss.theoj.org/papers/b40f03cc069b43b341a92bd26b660f35

We should add a link to the documentation.

**Comment by kpolimis** [comment]
added a JOSS status badge linking to the paper in the README
