### ISSUE TITLE
Usage in practised application

### ISSUE THREAD

**Issue by JIAZHEN** [scikit-learn-contrib/forest-confidence-interval#71]
Hi,

Firstly, thanks for the amazing work! I just have a question that how we support to use the error bar? Specifically for the RandomForestClassifier. The example only uses the result for plotting ...

Thanks and look forward to hearing from you

**Comment by arokem** [comment]
Sorry - I don't understand the question. What do you mean by "how we support to use the error bar"? You can plot it, as we show in the examples, but the number itself can be used in any type of inference that you usually do with error estimates.

**Comment by JIAZHEN** [comment]
Hi @arokem, Sorry, type - `support` -> `suppose`. 

- With the number, how would we measure the confidence interval of Random Forest? 
- In the example, the number named `Standard deviation`, what is this Standard deviation to? 
- do you have an example to say: here is my predict probability for a X, model predicted it as `class Foo`, by using this number I can say I'm 95%~100% confident the prediction is correct?

Thanks for answering

**Comment by arokem** [comment]
I'd recommend reading the Wager paper on which this is based, and which
explains all this: http://jmlr.org/papers/volume15/wager14a/wager14a.pdf

**Comment by JIAZHEN** [comment]
Though there could be existing examples to demonstrate the paper, I guess you're right to read it. Thanks for the replies.
