### ISSUE TITLE
random_forest_error() does not work without scalers.

### ISSUE THREAD

**Issue by chahakmehta** [scikit-learn-contrib/forest-confidence-interval#83]
Hi, 

I was using the random_forest_error() function for a project of mine where the data is of the order of 10,000 and if I used it without a scaler, it started giving NaN values for all points. Why would this be happening?

Furthermore, if I then used a MinMaxScaler for the same, then it gives some values but it doesn't work with StandardScaler. Any idea why that would happen?

Another question that I had was that I need the variances in the same order as the original data, i.e. of the order of the original output data. How can I rescale the variance so that it matches the order of the original data?

**Comment by danieleongari** [comment]
improved in v0.7
