### ISSUE TITLE
Warning: sklearn.ensemble.forest module is deprecated in version 0.22 

### ISSUE THREAD

**Issue by sq5rix** [scikit-learn-contrib/forest-confidence-interval#86]
Hi, when I use forstci, which is great, I get the following warning, which is harmless for now:

The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.

It might hit us in the future

**Comment by vakowal** [comment]
I'm getting an error that I believe is related to this, which is keeping me from calculating confidence intervals.  When using `random_forest_error()` on a random forest estimator with `inbag=None`:

> File "C:\Python37\lib\site-packages\forestci\forestci.py", line 232, in random_forest_error
    inbag = calc_inbag(X_train.shape[0], forest)
  File "C:\Python37\lib\site-packages\forestci\forestci.py", line 65, in calc_inbag
    n_samples))
TypeError: _generate_sample_indices() missing 1 required positional argument: 'n_samples_bootstrap'`

Using
 - Python 3.7
 - sklearn version 0.22.1
 - forestci verison 0.3

**Comment by m0wer** [comment]
Same as @vakowal :(

**Comment by ashwinbhakre** [comment]
@vakowal did you manage to get around this error?

**Comment by arokem** [comment]
I believe this should be resolved in the version released earlier today. Please reopen if not.
